"""Manifest generation for sample packs."""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path


def build_manifest(
    pack_id: str,
    pack_name: str,
    preset: str,
    chaos: float,
    sources: list[dict],
    outputs: list[dict],
    tools_used: dict[str, str],
    errors: list[str] | None = None,
) -> dict:
    """Build a serializable manifest dict."""
    return {
        "manifest_version": 1,
        "pack_id": pack_id,
        "pack_name": pack_name,
        "preset": preset,
        "chaos": chaos,
        "created_at": datetime.now(timezone.utc).isoformat(),
        "sources": [
            {
                "filename": s.get("filename", "unknown"),
                "original_format": s.get("format", "wav"),
                "duration": s.get("duration", 0.0),
                "sample_rate": s.get("sample_rate", 48000),
            }
            for s in sources
        ],
        "outputs": [
            {
                "path": o["path"],
                "category": o.get("category", "unknown"),
                "recipe": o.get("recipe", "unknown"),
                "duration_seconds": o.get("duration", 0.0),
                "source": o.get("source", "unknown"),
                "tools": o.get("tools", []),
                "parameters": o.get("parameters", {}),
            }
            for o in outputs
        ],
        "tools_used": tools_used,
        "errors": errors or [],
    }


def write_manifest(manifest: dict, path: Path) -> Path:
    """Write manifest.json to disk."""
    path.write_text(json.dumps(manifest, indent=2, default=str), encoding="utf-8")
    return path


def build_tools_info(tools: dict) -> dict:
    """Build tools.json structure."""
    result = {}
    for name, info in tools.items():
        if isinstance(info, dict) and "available" in info:
            result[name] = {"available": info["available"], "version": info.get("version")}
        elif isinstance(info, dict):
            sub = {}
            for sub_name, sub_info in info.items():
                if hasattr(sub_info, "available"):
                    sub[sub_name] = {
                        "available": sub_info.available,
                        "version": sub_info.version,
                    }
            result[name] = {"available": True, "engines": sub}
    return result


def build_readme(pack_name: str, preset: str, chaos: float, outputs: list[dict]) -> str:
    """Generate README.txt for the pack ZIP."""
    lines = [
        f"Resample-Lab — Generated Sample Pack",
        f"===================================",
        f"",
        f"Pack: {pack_name or 'Untitled'}",
        f"Preset: {preset}",
        f"Chaos: {chaos:.2f}",
        f"Generated: {datetime.now(timezone.utc).isoformat()}",
        f"",
        f"---",
        f"",
        f"This sample pack was generated by Resample-Lab, a local-first",
        f"audio mutation lab. All processing used non-AI DSP.",
        f"",
        f"Contents:",
    ]
    for o in outputs:
        path = o.get("path", "?")
        recipe = o.get("recipe", "?")
        cat = o.get("category", "?")
        dur = o.get("duration", 0)
        lines.append(f"  {path}  [{cat}]  {recipe}  ({dur:.1f}s)")

    lines += [
        f"",
        f"---",
        f"",
        f"IMPORTANT: Generated samples may be loud or contain extreme",
        f"frequencies. Gain-stage before use in your projects.",
        f"",
        f"You are responsible for the rights to any source audio used.",
    ]
    return "\n".join(lines)
